spring.application.name=app-vpp-be
app.frontend.url=http://localhost:5173

spring.datasource.url=jdbc:mysql://localhost:3306/vpp_atbm
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Send to Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranquocminh15981@gmail.com
spring.mail.password=bgrm btho bpbq wnid
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
